### ISSUE TITLE
Better Drush support

### ISSUE THREAD

**Issue by zaporylie** [drupol/openlayers#26]
I would love to see here at least one command: `drush openlayers-revert (drush olr)`. Syntax:

`drush olr` (interactive mode)
`drush olr component` (reverts all overriden items of type component)
`drush olr component:machinename` (reverts only single item, called _machinename_)
`drush olr --all` (reverts everything - maps, controls, layers, sources, components, styles, etc.)

I can modify .drush.inc file and create PR if you'd like to have it in OL module.

**Comment by drupol** [comment]
Hello,

As we are still using CTools exports for file based configuration, it already exists and it's provided by CTools.
Check the command cter

````
drush cter -h
````
