### ISSUE TITLE
Annotation error

### ISSUE THREAD

**Issue by jry2000** [drupol/openlayers#27]
Hi team, 
I have freshly installed Drupal 7.41 and I am trying to install OpenLayers 3. When I enable module, I am receiving error regarding Annotation. 
![openlayers3-error](https://cloud.githubusercontent.com/assets/15802225/11094654/277a99b4-8891-11e5-8905-cfd312efdd8e.png)

Openlayers version: 
 openlayers-7.x-3.0-beta4.tar.gz 	

Site set-up: 
PHP 5.5
Drupal 7.41 - fresh install no configuration whatsoever. 

Before installing openlayers I have installed modules below  (sources included). 
http://ftp.drupal.org/files/projects/libraries-7.x-2.2.tar.gz
http://ftp.drupal.org/files/projects/registry_autoload-7.x-1.3.tar.gz
http://ftp.drupal.org/files/projects/ctools-7.x-1.9.tar.gz
http://ftp.drupal.org/files/projects/service_container-7.x-1.0-beta5.tar.gz
http://ftp.drupal.org/files/projects/jquery_update-7.x-2.7.tar.gz
http://ftp.drupal.org/files/projects/geocoder-7.x-1.2.tar.gz
http://ftp.drupal.org/files/projects/geophp-7.x-1.7.tar.gz
http://ftp.drupal.org/files/projects/views-7.x-3.13.tar.gz

in /sites/all/libraries I have 
geoPHP

I've found no resolution on google. 

Is there any way to fix this issue?

**Comment by jry2000** [comment]
It seems I found a solution. When a Website has Optimizer enabled, it seems Opcache erases comments and headers ... 

My solution was to add 

`php_flag opcache.enable Off` 
 into .htaccess

Source
https://duraturk.wordpress.com/2014/04/27/disable-opcache-per-site/

**Comment by drupol** [comment]
Ok good.

Can I close this ?

**Comment by jry2000** [comment]
Hi Pol, 

feel free to close this one. 



Cheers



Jerry


---------- Původní zpráva ----------

Od: Pol Dellaiera <notifications@github.com>

Komu: drupol/openlayers <openlayers@noreply.github.com>

Datum: 23. 11. 2015 15:39:05

Předmět: Re: [openlayers] Annotation error (#27)


"

Ok good.

Can I close this ?

—

Reply to this email directly or view it on GitHub
(https://github.com/drupol/openlayers/issues/27#issuecomment-158953555). 





"=
