### ISSUE TITLE
How to add OL extension?

### ISSUE THREAD

**Issue by jonataswalker** [drupol/openlayers#29]
Hi guys,

Not sure where to ask but I wrote [an extension](https://github.com/jonataswalker/ol3-geocoder) for OpenLayers and was asked how to add it to Drupal and couldn't answer.

Thanks.

**Comment by drupol** [comment]
This is super nice!

It's also super easy to make the Drupal module that goes with it.

Have a look at the control (OL3LayerSwitcher)[https://github.com/drupol/openlayers/tree/7.x-3.x/modules/openlayers_library/src/Plugin/Control/OL3LayerSwitcher] in the submodule Openlayers Library.
Just copy paste that module and rename it as you want, then make change in the files. You don't have to do anything else.

Once it's done, you have to create an Openlayers Control in Drupal, and you should see your control type in the select list.

Ping me again if you need more help, I'll be happy to contribute.

**Comment by drupol** [comment]
By the way, there's already a very nice [Geocoder JS Library](https://github.com/geocoder-php/geocoder-js) here, maybe you can use it instead of rewriting everything ?

**Comment by jonataswalker** [comment]
@drupol thanks for your help, when it's ready should I submit a PR to your project?

**Comment by drupol** [comment]
Sure that you can !

Actually, the Openlayers module can be a very easy solution to provide an UI for your extension. You can easily provide options to select which provider to use etc etc... 

Anyway, I let you work then I'll review and comment your PR. Don't hesitate if you have any question.

**Comment by IckZ** [comment]
WOW! Nice to see that there is already a discussion on this thread. @Jonatas: Did you get my mail? I could give you a vanilla install of drupal and openlayers with all dependencies if you want. 

@drupol: Excuse me but what do you mean with "Openlayers Control in Drupal"? I did not test it but do I have to register anywhere a field widget for openlayers if I copy the submodule which you have mentioned?

**Comment by jonataswalker** [comment]
> I could give you a vanilla install of drupal ...

I guess that's not the hard part. What I need is a time to study and prepare an environment to drupal and so on...

Of course you could handle a Pull Request to this thread.
